apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-scaler-role
rules:
  - apiGroups: ["apps"] # API group for deployments
    resources: ["deployments"] # Specific subresource for scaling
    verbs: ["get", "update", "list", "patch", "watch"]